### ISSUE TITLE
virtinst: VM creation fails: Could not open '/var/lib/libvirt/qemu/nvram/VmNotInstalled_VARS.fd'

### ISSUE THREAD

**Issue by skobyda** [cockpit-project/bots#3112] opened 2022-03-18 14:13 UTC
Downstream report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007916

**Comment by cockpituous** [comment] 2022-03-18 14:35
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testConfigureBeforeInstall (__main__.TestMachinesCreate)
Generating a RSA private key
...................++++
.............................................................................++++
writing new private key to 'key.pem'
-----

DevTools listening on ws://127.0.0.1:9400/devtools/browser/88f0b0aa-beac-4e4c-ae28-443234e98613
[0318/143222.248806:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0318/143222.250695:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0318/143222.257548:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0318/143222.259422:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0318/143222.262420:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is 
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> log: osinfo-detect command failed:  (process:12725): GLib-GIO-WARNING **: 14:32:31.167: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 21, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
> error: {"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to destroy domain 'VmNotInstalled'\nerror: Requested operation is not valid: domain is not running\nERROR    internal error: process exited while connecting to monitor: 2022-03-18T14:32:42.374709Z qemu-system-x86_64: -blockdev {\"driver\":\"file\",\"filename\":\"/var/lib/libvirt/qemu/nvram/VmNotInstalled_VARS.fd\",\"node-name\":\"libvirt-pflash1-storage\",\"auto-read-only\":true,\"discard\":\"unmap\"}: Could not open '/var/lib/libvirt/qemu/nvram/VmNotInstalled_VARS.fd': Permission denied\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start VmNotInstalled\notherwise, please restart your installation.\nCommand '['virt-install', '--connect', 'qemu:///system', '--quiet', '--name', 'VmNotInstalled', '--os-variant', 'fedora28', '--memory', 'memory=130,maxmemory=150', '--check', 'path_in_use=off', '--wait', '-1', '--noautoconsole', '--disk', 'path=/var/lib/libvirt/images/VmNotInstalled.qcow2,device=disk,boot_order=2,bus=virtio,readonly=off,shareable=off,discard=unmap,driver_name=qemu,driver_type=qcow2', '--network', 'network=default,mac=52:54:00:1d:5c:b3,model=virtio,boot_order=1,link_state=up', '--network', 'bridge=virbr0,mac=52:54:00:c5:2f:66,model=rtl8139,link_state=up', '--graphics', 'type=vnc,listen=127.0.0.1,port=-1', '--graphics', 'type=spice,listen=127.0.0.1', '--cdrom', '/var/lib/libvirt/novell.iso', '--autostart', '--vcpus', 'vcpus=2,maxvcpus=8,sockets=2,cores=2,threads=2', '--boot', 'uefi']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<stdin>\", line 289, in install_vm\n  File \"/usr/lib/python3.9/subprocess.py\", line 424, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib/python3.9/subprocess.py\", line 528, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--name', 'VmNotInstalled', '--os-variant', 'fedora28', '--memory', 'memory=130,maxmemory=150', '--check', 'path_in_use=off', '--wait', '-1', '--noautoconsole', '--disk', 'path=/var/lib/libvirt/images/VmNotInstalled.qcow2,device=disk,boot_order=2,bus=virtio,readonly=off,shareable=off,discard=unmap,driver_name=qemu,driver_type=qcow2', '--network', 'network=default,mac=52:54:00:1d:5c:b3,model=virtio,boot_order=1,link_state=up', '--network', 'bridge=virbr0,mac=52:54:00:c5:2f:66,model=rtl8139,link_state=up', '--graphics', 'type=vnc,listen=127.0.0.1,port=-1', '--graphics', 'type=spice,listen=127.0.0.1', '--cdrom', '/var/lib/libvirt/novell.iso', '--autostart', '--vcpus', 'vcpus=2,maxvcpus=8,sockets=2,cores=2,threads=2', '--boot', 'uefi']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<stdin>\", line 359, in <module>\n  File \"<stdin>\", line 300, in install_vm\n  File \"<stdin>\", line 289, in install_vm\n  File \"/usr/lib/python3.9/subprocess.py\", line 424, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib/python3.9/subprocess.py\", line 528, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--name', 'VmNotInstalled', '--os-variant', 'fedora28', '--memory', 'memory=130,maxmemory=150', '--check', 'path_in_use=off', '--wait', '-1', '--noautoconsole', '--disk', 'path=/var/lib/libvirt/images/VmNotInstalled.qcow2,device=disk,boot_order=2,bus=virtio,readonly=off,shareable=off,discard=unmap,driver_name=qemu,driver_type=qcow2', '--network', 'network=default,mac=52:54:00:1d:5c:b3,model=virtio,boot_order=1,link_state=up', '--network', 'bridge=virbr0,mac=52:54:00:c5:2f:66,model=rtl8139,link_state=up', '--graphics', 'type=vnc,listen=127.0.0.1,port=-1', '--graphics', 'type=spice,listen=127.0.0.1', '--cdrom', '/var/lib/libvirt/novell.iso', '--autostart', '--vcpus', 'vcpus=2,maxvcpus=8,sockets=2,cores=2,threads=2', '--boot', 'uefi']' returned non-zero exit status 1."}
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1566, in testConfigureBeforeInstall
    wait(lambda: "VmNotInstalled" in m.execute("virsh list --persistent"), delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 2141, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.
Wrote screenshot to TestMachinesCreate-testConfigureBeforeInstall-debian-testing-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestMachinesCreate-testConfigureBeforeInstall-debian-testing-127.0.0.2-2401-FAIL.html
Wrote JS log to TestMachinesCreate-testConfigureBeforeInstall-debian-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestMachinesCreate-testConfigureBeforeInstall-debian-testing-127.0.0.2-2401-FAIL.log.gz
audit: type=1400 audit(1647613962.364:66): apparmor="DENIED" operation="open" profile="libvirt-d90cee25-e388-4dfe-a7a1-599970d31984" name="/var/lib/libvirt/qemu/nvram/VmNotInstalled_VARS.fd" pid=12959 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=64055
Wrote JS log to TestMachinesCreate-testConfigureBeforeInstall-debian-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestMachinesCreate-testConfigureBeforeInstall-debian-testing-127.0.0.2-2401-FAIL.log.gz
umount: /usr/share/OVMF: not mounted.
bash: line 1: rpm: command not found
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1647614145778.595,"url":"http://127.0.0.2:9291/machines#vm?name=VmNotInstalled&connection=system"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-admin.socket
  libvirtd.socket
  libvirtd-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1566, in testConfigureBeforeInstall
    wait(lambda: "VmNotInstalled" in m.execute("virsh list --persistent"), delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 2141, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.

# Result testConfigureBeforeInstall (__main__.TestMachinesCreate) failed
# 1 TEST FAILED [209s on 3-ci-srv-02]
not ok 6 /work/bots/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testConfigureBeforeInstall [ND@2]
```
First occurrence: 2022-03-18T14:35:48.079504 | revision bf65b3d2f4f00eb56197715321192af2c6b72016
Times recorded: 1
Latest occurrences:

- 2022-03-18T14:35:48.079504 | revision bf65b3d2f4f00eb56197715321192af2c6b72016

**Comment by martinpitt** [comment] 2022-03-18 14:39
This is a duplicate of issue #2991. We've had PR #2992 open for a while, as so far it only affected https://github.com/cockpit-project/cockpit-machines/pull/583 . But if that affects the main branch now, we need to land the naughty now (which is fiine for me).

**Closed by martinpitt** 2022-03-18 14:39 UTC
Labels: knownissue
