### ISSUE TITLE
Cannot store coredumps with s3

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#3565] opened 2022-06-28 11:08 UTC
As seen in https://github.com/cockpit-project/bots/pull/3487

Apparently our signature computation fails with the funny names like

    https://cockpit-logs.us-east-1.linodeobjects.com/pull-3487-20220628-063920-258f5211-rhel-7-9-cockpit-project-cockpit-rhel-7.9/TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-2501-FAIL.core/.#core.curl.0.bcee2fb1597b435c9400e2e8770a4b3d.1844.1656399156000000.xzbe9b94700088d65b

So that might need some quoting.

From logs:
```
cockpit-tasks-3[2015068]: INFO:root:Consuming message with command: ./s3-streamer --repo cockpit-project/bots --test-name pull-3487-20220623-114834 --github-context rhel-7-9@cockpit-project/cockpit/rhel-7.9 --revision 258f52114bd18a530747261ada2b78e136ed3eaa -- /bin/sh -c "PRIORITY=0005 ./make-checkout --verbose --repo=cockpit-project/cockpit rhel-7.9 && cd make-checkout-workdir && TEST_OS=rhel-7-9 BASE_BRANCH=rhel-7.9 COCKPIT_BOTS_REF=258f52114bd18a530747261ada2b78e136ed3eaa ../tests-invoke --pull-number 3487 --revision 258f52114bd18a530747261ada2b78e136ed3eaa --repo cockpit-project/bots"
podman[2014657]: INFO:root:Consuming message with command: ./s3-streamer --repo cockpit-project/bots --test-name pull-3487-20220623-114834 --github-context rhel-7-9@cockpit-project/cockpit/rhel-7.9 --revision 258f52114bd18a530747261ada2b78e136ed3eaa -- /bin/sh -c "PRIORITY=0005 ./make-checkout --verbose --repo=cockpit-project/cockpit rhel-7.9 && cd make-checkout-workdir && TEST_OS=rhel-7-9 BASE_BRANCH=rhel-7.9 COCKPIT_BOTS_REF=258f52114bd18a530747261ada2b78e136ed3eaa ../tests-invoke --pull-number 3487 --revision 258f52114bd18a530747261ada2b78e136ed3eaa --repo cockpit-project/bots"
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:GitHub repo cockpit-project/bots context rhel-7-9@cockpit-project/cockpit/rhel-7.9 link https://cockpit-logs.us-east-1.linodeobjects.com/pull-3487-20220623-114834-258f5211-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html
podman[2014657]: DEBUG:s3-streamer:GitHub repo cockpit-project/bots context rhel-7-9@cockpit-project/cockpit/rhel-7.9 link https://cockpit-logs.us-east-1.linodeobjects.com/pull-3487-20220623-114834-258f5211-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:Uploading attachment log.html
podman[2014657]: DEBUG:s3-streamer:Uploading attachment log.html
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:POST statuses/258f52114bd18a530747261ada2b78e136ed3eaa pending Testing in progress [3-ci-srv-05]
podman[2014657]: DEBUG:s3-streamer:POST statuses/258f52114bd18a530747261ada2b78e136ed3eaa pending Testing in progress [3-ci-srv-05]
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-services-127.0.0.2-3002-FAIL.log
podman[2014657]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-services-127.0.0.2-3002-FAIL.log
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.log
podman[2014657]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.log
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:Uploading attachment TestSubscriptions-testSubAndInAndFail-services-127.0.0.2-2702-FAIL.log
podman[2014657]: DEBUG:s3-streamer:Uploading attachment TestSubscriptions-testSubAndInAndFail-services-127.0.0.2-2702-FAIL.log
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.core/core.curl.0.f0bd46a22c1843b7abe900b29eb4223b.1735.1655985804000000.xz
podman[2014657]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.core/core.curl.0.f0bd46a22c1843b7abe900b29eb4223b.1735.1655985804000000.xz
cockpit-tasks-3[2015068]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.core/.#core.curl.0.f0bd46a22c1843b7abe900b29eb4223b.1755.1655985816000000.xz940c81860269648b
podman[2014657]: DEBUG:s3-streamer:Uploading attachment TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.core/.#core.curl.0.f0bd46a22c1843b7abe900b29eb4223b.1755.1655985816000000.xz940c81860269648b
cockpit-tasks-3[2015068]: DEBUG:s3:PUT https://cockpit-logs.us-east-1.linodeobjects.com/pull-3487-20220623-114834-258f5211-rhel-7-9-cockpit-project-cockpit-rhel-7.9/TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.core/.#core.curl.0.f0bd46a22c1843b7abe900b29eb4223b.1755.1655985816000000.xz940c81860269648b {'content-type': 'text/plain', 'x-amz-acl': 'public-read', 'host': 'cockpit-logs.us-east-1.linodeobjects.com', 'x-amz-content-sha256': 'efe7b1fff66525b3aefeaa7efae614590ce9ea37b4878bd740378bcb8c61b6e8', 'x-amz-date': '20220623T120350Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=YX0BE5CGRW5W1TBB4APX/20220623/any/s3/aws4_request,SignedHeaders=content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date,Signature=d3031bcf072d6afa212b747bdc9c57b5dc7bd0290b01f4f70f92b398ba88a612'} → 403:
podman[2014657]: DEBUG:s3:PUT https://cockpit-logs.us-east-1.linodeobjects.com/pull-3487-20220623-114834-258f5211-rhel-7-9-cockpit-project-cockpit-rhel-7.9/TestSubscriptionsPackages-testMissingPackages-rhel-7-9-127.0.0.2-3001-FAIL.core/.#core.curl.0.f0bd46a22c1843b7abe900b29eb4223b.1755.1655985816000000.xz940c81860269648b {'content-type': 'text/plain', 'x-amz-acl': 'public-read', 'host': 'cockpit-logs.us-east-1.linodeobjects.com', 'x-amz-content-sha256': 'efe7b1fff66525b3aefeaa7efae614590ce9ea37b4878bd740378bcb8c61b6e8', 'x-amz-date': '20220623T120350Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=YX0BE5CGRW5W1TBB4APX/20220623/any/s3/aws4_request,SignedHeaders=content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date,Signature=d3031bcf072d6afa212b747bdc9c57b5dc7bd0290b01f4f70f92b398ba88a612'} → 403:
cockpit-tasks-3[2015068]: DEBUG:s3:  b'<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx00000000000000bcce224-0062b456a7-1946d691-default</RequestId><HostId>1946d691-default-default</HostId></Error>'
podman[2014657]: DEBUG:s3:  b'<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx00000000000000bcce224-0062b456a7-1946d691-default</RequestId><HostId>1946d691-default-default</HostId></Error>'
cockpit-tasks-3[2015068]: Traceback (most recent call last):
cockpit-tasks-3[2015068]:   File "/work/bots/./s3-streamer", line 351, in <module>
podman[2014657]: Traceback (most recent call last):
podman[2014657]:   File "/work/bots/./s3-streamer", line 351, in <module>
podman[2014657]:     main()
podman[2014657]:   File "/work/bots/./s3-streamer", line 337, in main
podman[2014657]:     attachments_directory.scan()
podman[2014657]:   File "/work/bots/./s3-streamer", line 158, in scan
cockpit-tasks-3[2015068]:     main()
podman[2014657]:     self.destination.write(name, data)
podman[2014657]:   File "/work/bots/./s3-streamer", line 118, in write
podman[2014657]:     self.destination.write(filename, data)
podman[2014657]:   File "/work/bots/./s3-streamer", line 97, in write
podman[2014657]:     with s3.urlopen(self.url(filename), data=data, method='PUT', headers=headers) as _:
podman[2014657]:   File "/work/bots/lib/s3.py", line 117, in urlopen
podman[2014657]:     response = urllib.request.urlopen(request, context=host_ssl_context(url.netloc))
podman[2014657]:   File "/usr/lib64/python3.10/urllib/request.py", line 216, in urlopen
cockpit-tasks-3[2015068]:   File "/work/bots/./s3-streamer", line 337, in main
cockpit-tasks-3[2015068]:     attachments_directory.scan()
cockpit-tasks-3[2015068]:   File "/work/bots/./s3-streamer", line 158, in scan
cockpit-tasks-3[2015068]:     self.destination.write(name, data)
cockpit-tasks-3[2015068]:   File "/work/bots/./s3-streamer", line 118, in write
cockpit-tasks-3[2015068]:     self.destination.write(filename, data)
cockpit-tasks-3[2015068]:   File "/work/bots/./s3-streamer", line 97, in write
cockpit-tasks-3[2015068]:     with s3.urlopen(self.url(filename), data=data, method='PUT', headers=headers) as _:
cockpit-tasks-3[2015068]:   File "/work/bots/lib/s3.py", line 117, in urlopen
cockpit-tasks-3[2015068]:     response = urllib.request.urlopen(request, context=host_ssl_context(url.netloc))
cockpit-tasks-3[2015068]:   File "/usr/lib64/python3.10/urllib/request.py", line 216, in urlopen
cockpit-tasks-3[2015068]:     return opener.open(url, data, timeout)
cockpit-tasks-3[2015068]:   File "/usr/lib64/python3.10/urllib/request.py", line 525, in open
podman[2014657]:     return opener.open(url, data, timeout)
podman[2014657]:   File "/usr/lib64/python3.10/urllib/request.py", line 525, in open
cockpit-tasks-3[2015068]:     response = meth(req, response)
podman[2014657]:     response = meth(req, response)
podman[2014657]:   File "/usr/lib64/python3.10/urllib/request.py", line 634, in http_response
cockpit-tasks-3[2015068]:   File "/usr/lib64/python3.10/urllib/request.py", line 634, in http_response
cockpit-tasks-3[2015068]:     response = self.parent.error(
podman[2014657]:     response = self.parent.error(
podman[2014657]:   File "/usr/lib64/python3.10/urllib/request.py", line 563, in error
cockpit-tasks-3[2015068]:   File "/usr/lib64/python3.10/urllib/request.py", line 563, in error
cockpit-tasks-3[2015068]:     return self._call_chain(*args)
cockpit-tasks-3[2015068]:   File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
podman[2014657]:     return self._call_chain(*args)
podman[2014657]:   File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
cockpit-tasks-3[2015068]:     result = func(*args)
cockpit-tasks-3[2015068]:   File "/usr/lib64/python3.10/urllib/request.py", line 643, in http_error_default
podman[2014657]:     result = func(*args)
podman[2014657]:   File "/usr/lib64/python3.10/urllib/request.py", line 643, in http_error_default
podman[2014657]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
cockpit-tasks-3[2015068]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
cockpit-tasks-3[2015068]: urllib.error.HTTPError: HTTP Error 403: Forbidden
podman[2014657]: urllib.error.HTTPError: HTTP Error 403: Forbidden
cockpit-tasks-3[2015068]: ERROR:root:./s3-streamer --repo cockpit-project/bots --test-name pull-3487-20220623-114834 --github-context rhel-7-9@cockpit-project/cockpit/rhel-7.9 --revision 258f52114bd18a530747261ada2b78e136ed3eaa -- /bin/sh -c "PRIORITY=0005 ./make-checkout --verbose --repo=cockpit-project/cockpit rhel-7.9 && cd make-checkout-workdir && TEST_OS=rhel-7-9 BASE_BRANCH=rhel-7.9 COCKPIT_BOTS_REF=258f52114bd18a530747261ada2b78e136ed3eaa ../tests-invoke --pull-number 3487 --revision 258f52114bd18a530747261ada2b78e136ed3eaa --repo cockpit-project/bots" failed with exit code 1
podman[2014657]: ERROR:root:./s3-streamer --repo cockpit-project/bots --test-name pull-3487-20220623-114834 --github-context rhel-7-9@cockpit-project/cockpit/rhel-7.9 --revision 258f52114bd18a530747261ada2b78e136ed3eaa -- /bin/sh -c "PRIORITY=0005 ./make-checkout --verbose --repo=cockpit-project/cockpit rhel-7.9 && cd make-checkout-workdir && TEST_OS=rhel-7-9 BASE_BRANCH=rhel-7.9 COCKPIT_BOTS_REF=258f52114bd18a530747261ada2b78e136ed3eaa ../tests-invoke --pull-number 3487 --revision 258f52114bd18a530747261ada2b78e136ed3eaa --repo cockpit-project/bots" failed with exit code 1
```

**Comment by allisonkarlitskaya** [comment] 2024-04-21 09:52
This is caused by the `#` and is almost definitely fixed by https://github.com/cockpit-project/bots/pull/6115

**Closed by allisonkarlitskaya** 2024-04-21 09:52 UTC
